In [31]:
import pandas as pd
train=pd.read_csv("http://bit.ly/kaggletrain")
train.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [0]:
train.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [34]:
pd.get_dummies(train,columns=['Sex','Embarked'],drop_first=True)

     PassengerId  Survived  Pclass  ... Sex_male  Embarked_Q  Embarked_S
0              1         0       3  ...        1           0           1
1              2         1       1  ...        0           0           0
2              3         1       3  ...        0           0           1
3              4         1       1  ...        0           0           1
4              5         0       3  ...        1           0           1
5              6         0       3  ...        1           1           0
6              7         0       1  ...        1           0           1
7              8         0       3  ...        1           0           1
8              9         1       3  ...        0           0           1
9             10         1       2  ...        0           0           0
10            11         1       3  ...        0           0           1
11            12         1       1  ...        0           0           1
12            13         0       3  ...        1           0           1
13            14         0       3  ...        1           0           1
14            15         0       3  ...        0           0           1
15            16         1       2  ...        0           0           1
16            17         0       3  ...        1           1           0
17            18         1       2  ...        1           0           1
18            19         0       3  ...        0           0           1
19            20         1       3  ...        0           0           0
20            21         0       2  ...        1           0           1
21            22         1       2  ...        1           0           1
22            23         1       3  ...        0           1           0
23            24         1       1  ...        1           0           1
24            25         0       3  ...        0           0           1
25            26         1       3  ...        0           0           1
26            27         0       3  ...        1           0           0
27            28         0       1  ...        1           0           1
28            29         1       3  ...        0           1           0
29            30         0       3  ...        1           0           1
..           ...       ...     ...  ...      ...         ...         ...
861          862         0       2  ...        1           0           1
862          863         1       1  ...        0           0           1
863          864         0       3  ...        0           0           1
864          865         0       2  ...        1           0           1
865          866         1       2  ...        0           0           1
866          867         1       2  ...        0           0           0
867          868         0       1  ...        1           0           1
868          869         0       3  ...        1           0           1
869          870         1       3  ...        1           0           1
870          871         0       3  ...        1           0           1
871          872         1       1  ...        0           0           1
872          873         0       1  ...        1           0           1
873          874         0       3  ...        1           0           1
874          875         1       2  ...        0           0           0
875          876         1       3  ...        0           0           0
876          877         0       3  ...        1           0           1
877          878         0       3  ...        1           0           1
878          879         0       3  ...        1           0           1
879          880         1       1  ...        0           0           0
880          881         1       2  ...        0           0           1
881          882         0       3  ...        1           0           1
882          883         0       3  ...        0           0           1
883          884         0       2  ...        1           0           1
884          885         0       3  ...        1           0           1
885          886         0       3  ...        0           1           0
886          887         0       2  ...        1           0           1
887          888         1       1  ...        0           0           1
888          889         0       3  ...        0           0           1
889          890         1       1  ...        1           0           0
890          891         0       3  ...        1           1           0

[891 rows x 13 columns]

In [0]:
E_dum=pd.get_dummies(train.Embarked,prefix='Embarked').iloc[:,1:]

In [30]:
train=pd.concat([train,E_dum],axis=1)
train.head()

   PassengerId  Survived  Pclass  ... Embarked Embarked_Q  Embarked_S
0            1         0       3  ...        S          0           1
1            2         1       1  ...        C          0           0
2            3         1       3  ...        S          0           1
3            4         1       1  ...        S          0           1
4            5         0       3  ...        S          0           1

[5 rows x 14 columns]

In [0]:
pd.get_dummies(train.Sex,prefix='Sex').iloc[:,1:]

     Sex_male
0           1
1           0
2           0
3           0
4           1
5           1
6           1
7           1
8           0
9           0
10          0
11          0
12          1
13          1
14          0
15          0
16          1
17          1
18          0
19          0
20          1
21          1
22          0
23          1
24          0
25          0
26          1
27          1
28          0
29          1
..        ...
861         1
862         0
863         0
864         1
865         0
866         0
867         1
868         1
869         1
870         1
871         0
872         1
873         1
874         0
875         0
876         1
877         1
878         1
879         0
880         0
881         1
882         0
883         1
884         1
885         0
886         1
887         0
888         0
889         1
890         1

[891 rows x 1 columns]